### ISSUE TITLE
Missing some web metrics on NetCore App

### ISSUE THREAD

**Issue by jbbws** [AppMetrics/AspNetCore#12]
Sorry for my English. I'm using AppMetrics for measuring performance of my app. My app is being developed on Net Core 2.I'm using built-in web metric and displaying them with Grafana. I've imported dash-2125, and config data source from influxdb. All works good, but some metrics doesn't measured, and grafana panel write "No data to show". Grafana is trying select application.httprequests_exceptions measurement but influx db has't that measurement (click on img).
![grafana](https://user-images.githubusercontent.com/20383607/36422836-c35f0eb2-164e-11e8-87ab-8e5f66d33ac7.png)
Influx show me these measurements (there is no httprequests_exceptions measurement)
![default](https://user-images.githubusercontent.com/20383607/36423032-70a00c52-164f-11e8-9152-17db19d89fda.png)
Can you explain me how to get missing metrics? I'm bootstrapping my Startup.cs and using UseMetricsAllMiddleware() and AddMetricsTrackingMiddleware().

**Comment by alhardy** [comment]
Try referring to the [aspnet core 2](https://github.com/AppMetrics/Samples.V2/tree/master/AspNetCore2.Api.QuickStart).

Note that at the moment, only uncaught exceptions are tracked.

**Comment by jbbws** [comment]
Thanks you)And one more question. How to corretcly using pre-defined health checking in order to report them to influxdb? I'm trying differnet way to include simple health checking(ping to google), but they not send to influx and not dispaly in grafana

**Comment by alhardy** [comment]
Ah I've had this question several times, I ended up removing that functionality when decoupling heath and metrics as Microsoft now also have a health check implementation for aspnet core which is very similar.

I do have plans to report health results in a future release but for now you'll have to roll your own unfortunately.

**Comment by maxisam** [comment]
@alhardy  i wish you can put this in the document. 'I do have plans to report health results in a future release but for now you'll have to roll your own unfortunately.'

I was trying to figure out why it doesn't send to influxdb.
