### ISSUE TITLE
Apdex Metrics doesn't working

### ISSUE THREAD

**Issue by jbbws** [AppMetrics/AspNetCore#14]
Hello Allan. I have one more problem with Web Metrics. I've added middlware with  using UseMetricsAllMiddleware(), than i trying test app by Apache Benchmark. In overview section Apdex measure always set 1 (in appsetting.json: MetricsWebTrackingOptions : ApdexTSeconds = 0.0001, ApdexTrackingEnabled = true) 
![default](https://user-images.githubusercontent.com/20383607/36903182-086ca716-1e3e-11e8-86e2-08e27df36e59.png)
And Endpoints section does not work correctly. I'm trying get request to concrete existing root, my app successfully return json, as needed. But route metrics doesn't collect 
![default](https://user-images.githubusercontent.com/20383607/36903556-20f88df8-1e3f-11e8-90b9-958c33d5c8f3.png)
There is should be route with Response time and Throughput but there is no data to show. Can you explain me how it's work, maybe i missed some configuration? (appsetting.json below)
![default](https://user-images.githubusercontent.com/20383607/36903848-f59eddf0-1e3f-11e8-84c2-98ddfe965b8d.png)

**Comment by alhardy** [comment]
What reporter are you using? I would start by running the aspnet core sandbox project e.g. if you are using InfluxDB try running https://github.com/AppMetrics/InfluxDB/tree/master/sandbox/MetricsInfluxDBSandboxMvc
