### ISSUE TITLE
how  OAuth2 Client Web Monitoring?

### ISSUE THREAD

**Issue by kongkong56** [AppMetrics/AspNetCore#15]
Idont know how OAuth2 Client Web Monitoring ?Please give a brief introduction 

Before logging a new issue, please have a quick read through the [contribution guidlines](https://github.com/alhardy/AppMetrics/blob/master/CONTRIBUTING.md).

**Comment by alhardy** [comment]
Does this help? https://www.app-metrics.io/web-monitoring/aspnet-core/tracking-middleware/
