### ISSUE TITLE
Metrics per endpoint not working with AddMvcCore

### ISSUE THREAD

**Issue by MaxDeg** [AppMetrics/AspNetCore#16]
### Issue
Metrics per endpoint is working well if you configure your application using AddMvc. But if you use AddMvcCore the proper configuration is not set and thus those metrics aren't collected.

### workaround

Adding manually the filter in the case of AddMvcCore is fixing the issue.
```csharp
services.AddMvcCore(opts => opts.Filters.Add(new MetricsResourceFilter(new MvcRouteTemplateResolver())));
```

**Comment by alhardy** [comment]
Metrics will still be collected, you won't however have them tagged by their MVC route template. 

The idea of `AddMvcCore` is more control and having minimal dependancies therefore leaves you doing more manual configuration.

In saying that, what would you like to see coming out of this issue?

**Comment by MaxDeg** [comment]
Indeed seen like that it make sense.
In that case I don't think any modification in the code is required. Maybe only a note about that in the documentation could be useful.
