### ISSUE TITLE
Response time is too slow.

### ISSUE THREAD

**Issue by winty56** [AppMetrics/AspNetCore#19]
I'm Using Tracking Middleware. 
I measured response time using jmeter. but AppMetrics is too slow.
when I test without AppMetrics, response time is about 50ms. 
but with AppMetrics, response time is about 200ms.
also after increase thread count Its response mean time is over 10000ms. 
What did I do wrong?
Is there any benchmark report about 'aspnetcore'?

**Comment by alhardy** [comment]
Shouldn't be the case. I have not aspnetcore specific benchmarks but haven't noticed this in my production apps, the aspnetcore packages basically contain middleware and helpers for bootstrapping and configuration. Under the covers it uses various metric type implementations, you can find benchmarks for those [here ](https://github.com/AppMetrics/AppMetrics/tree/dev/benchmarks/App.Metrics.Benchmarks.Runner/BenchmarkDotNet.Artifacts/results)

**Comment by alhardy** [comment]
@winty56 I ran a quick load test hosting the aspnetcore app metrics sample app on an azure appservice instance, single core with 250 concurrent users for 5 mins, don't see much of a difference.

Will share a benchmark report when I get around to it

**Comment by winty56** [comment]
@alhardy I found reason. It because logger setting... my default log level is 'all'. so all of AppMetrics' debug log being logged and I/O process have many CPU resource. It is all my fault. Sorry for the confusion.

**Comment by alhardy** [comment]
@winty56 awesome thanks for coming back with the explanation. Yeah AppMetrics spits out a fair bit at a trace level
