### ISSUE TITLE
MvcRouteTemplateResolver.ExtractRouteTemplete method throw NullReference Exception

### ISSUE THREAD

**Issue by winty56** [AppMetrics/AspNetCore#20]
## Problem 
when using mvc metrics ( `services.AddMvc().AddMetrics();`) and call http request, this error is occur.
![image](https://user-images.githubusercontent.com/20895025/38597642-d18a4e68-3d93-11e8-9fa0-715bc0d06663.png)

## Environment
I use `swagger` and `Microsoft.AspNetCore.Mvc.Versioning` 

## This happens because of this
I try debug and found the exact reason.

`App.Metrics.AspNetCore.Mvc.MvcRouteTemplateResolver.cs` 
```C#
private static string ExtractRouteTemplate(RouteData routeData, ActionDescriptor actionDescriptor)
{
    var routeTemplate = actionDescriptor.AttributeRouteInfo?.Template.ToLower() ?? string.Empty;

    if (actionDescriptor.Properties != null && actionDescriptor.Properties.ContainsKey(MsVersionpolicyIsAppliedToken))
    {
        routeTemplate = routeTemplate.Replace(ApiVersionToken, routeData.Values[VersionRouteDataToken].ToString());
    }

    return routeTemplate;
}
```
`routeData.Values[VersionRouteDataToken]` is null. so `ToString()` method throw exception. 

It seems that the string `{version: apiversion}` does not exist in path, even though I use versioning to have `MsVersionpolicyIsAppliedToken`

## My Solution 
I added code to check if 'ApiVersionToken' exists before replace.

``` C#
if (routeTemplate.Contains(ApiVersionToken))
{
    routeTemplate = routeTemplate.Replace(ApiVersionToken, routeData.Values[VersionRouteDataToken].ToString());
}
```

My project works fine after apply this modify.
but I don't know that my solution is correct. plz check this issue.

**Comment by alhardy** [comment]
Interesting, I did apply some fixes around some of my own APIs using aspnet core mvc versioning a few months back. Will investigate, although your check does seem like a valid one, maybe a PR?

Would still like to investigate further based on your usage of aspnet core mvc versioning i.e. should versioning be applied with your configuration.

Could you share a snippet or repo which replicates the issue?

**Comment by winty56** [comment]
I am sorry that I could not share my project repository. 
but this problem is easy to reproduce.

`Startup.cs`
  - I just copy and apply this code in below document.
    - https://github.com/Microsoft/aspnet-api-versioning/wiki/API-Documentation#aspnet-core
```C#
services.AddMvcCore().AddVersionedApiExplorer(o => o.GroupNameFormat = "'v'VVV");

services.AddApiVersioning(o => {
    o.ReportApiVersions = true;
    o.AssumeDefaultVersionWhenUnspecified = true;
    o.DefaultApiVersion = new ApiVersion(1, 0);
});
            
services.AddSwaggerGen(c =>
{
    var provider = services.BuildServiceProvider().GetRequiredService<IApiVersionDescriptionProvider>();
    foreach (var description in provider.ApiVersionDescriptions)
    {
        c.SwaggerDoc(description.GroupName, CreateInfoForApiVersion(description));
    }

    c.OperationFilter<SwaggerDefaultValues>();
                
    if (!string.IsNullOrEmpty(this.xmlPath))
    {
        c.IncludeXmlComments(this.xmlPath);
    }
    c.DescribeAllEnumsAsStrings();
});
```

`MVC Controller`
```C#
[ApiVersion("1.0")]
[Route("test")]
public class TestController
{
    [HttpGet("test")]
    public string GetTest()
    {
        return "test";
    }
}
```

when request `/test/test`, this error maybe occur.

**Comment by alexquintero** [comment]
I think this the same issue as [Issue 254](https://github.com/AppMetrics/AppMetrics/issues/254) which was fixed in a PR already. I mistakenly made the duplicate issue because I didn't see this one in the other repo.
