### ISSUE TITLE
why apdex score is always 1,but satisfied ,tolerated is always 0?

### ISSUE THREAD

**Issue by kongkong56** [AppMetrics/AspNetCore#22]
mean_score | mean_satisfied | mean_tolerating | mean_frustrating | mean_samples
-- | -- | -- | -- | --
  |   |   |   |  
1 | 0 | 0 | 0 | 0
1 | 0 | 0 | 0 | 0
1 | 0 | 0 | 0 | 0
1 | 0 | 0 | 0 | 0
1 | 0 | 0 | 0 | 0
1 | 0 | 0 | 0 | 0
1 | 0 | 0 | 0 | 0
1 | 0 | 0 | 0 | 0
1 | 0 | 0 | 0 | 0
1 | 0 | 0 | 0 | 0
1 | 0 | 0 | 0 | 0
1 | 0 | 0 | 0 | 0
1 | 0 | 0 | 0 | 0
1 | 0 | 0 | 0 | 0
1 | 0 | 0 | 0 | 0
1 | 0 | 0 | 0 | 0

Before logging a new issue, please have a quick read through the [contribution guidlines](https://github.com/alhardy/AppMetrics/blob/master/CONTRIBUTING.md).

**Comment by alhardy** [comment]
Looks like a but in the middleware configuration.
