### ISSUE TITLE
Allow Reporter to reset metric valuesource and/or reservoir.

### ISSUE THREAD

**Issue by WillGunn** [AppMetrics/AspNetCore#24]
Maybe this is the wrong approach, if so please let me know.

I've written a custom reporter that converts the ApdexValueSource, MeterValueSource, and TimerValueSource to a custom object, then serializes them individually to a custom data logger we use every 60 seconds.  This is working fine.  I am currently using the default set of metrics.

What I'm looking to do is be able to reset those 3 valuesources after the FlushAsync call of the reporter has finished, mostly so that the count, max, and min values get reset so they are accurate for the 60 second block that is being logged, and are not the max and min of the lifetime of the process.

There doesn't seem to be any documentation on how to reset counters from the AspNetCore wrapper, and the mentions of reseting in the Getting Started section seem to only deal with creating new instances of a MetricType, with nothing about how to control the default set of metrics provided.

~~I can get the min and max to change using the sliding window reservoir, but the count (from timer.Value.Histogram.Count) doesn't seem to be affected and shows the total count, not the count in the sliding window.~~

**Comment by alhardy** [comment]
@WillGunn yeah there isn't any control over the configuration of metrics recorded in the AspNet Core middleware. Unfortuntely you would at the moment have to implement the customisations you're after yourself, I don't have plans to make this configurable at the moment but I'll keep it in mind and revisit if others require.
