### ISSUE TITLE
Configuring endpoints with AllEndpointsPort for alternate port binds only to localhost, not 0.0.0.0, when using WebHost

### ISSUE THREAD

**Issue by Bob11327** [AppMetrics/AspNetCore#28]
The project documentation (https://www.app-metrics.io/web-monitoring/aspnet-core/endpoint-middleware/) shows that the metrics can be exposed on a specific port by specifying the AllEndpointsPort configuration property, for example 9335.

In the source code to the project, when building this out with the IWebHost object interface (https://github.com/AppMetrics/AspNetCore/blob/dev/src/App.Metrics.AspNetCore.Endpoints/Builder/MetricsAspNetEndpointWebHostBuilderExtensions.cs), line 165 (towards end of ConfigureAppMetricsHostingConfiguration method, appears to be extending the list of URLs the WebHost should service with the AllEndpointsPort port value but explicitly on the http://localhost:<port> path.

This makes the metrics accessible on the default/primary URL, e.g. at http://servername/metrics, and additionally at http://localhost:9335/”.  However, because the binding specified is “localhost” and not "*", port 9335 is not accessible off-box.

**Comment by alhardy** [comment]
Fixed by #29
