### ISSUE TITLE
QUESTION: Setup Tracking for Endpoints

### ISSUE THREAD

**Issue by caseylobrien** [AppMetrics/AspNetCore#31]
Hey!

Have an app where we have been using App.Metrics for a few months, works great!

I am currently trying to implement the Tracking (Web Metrics) for our endpoints. Now as I read it (https://www.app-metrics.io/web-monitoring/aspnet-core/tracking-middleware/), after I bootstrap in the startup.cs (app.UseMetricsAllMiddleware() and services.AddMetricsTrackingMiddleware()) that I should start to see the metrics for all the endpoints. Currently, I am only see an empty Apdex (guessing that is now fixed https://github.com/AppMetrics/AspNetCore/issues/22) but nothing from the endpoints.

I found https://github.com/AppMetrics/AspNetCore/issues/16 and tried his work around as we are using AddMvc and AddMvcCore but still not getting metrics. Can you think of anything else that I should try (or something that I have done incorrectly more like) ? 

Environment:
OS: Windows 10
IDE: Visual Studio Professional 2017 15.7.3
Target Platform: net core 2.1

Thanks!

**Comment by alhardy** [comment]
What does your startup.cs look like?

Easiest way to configure with defaults is to simply call `UseMetrics` on the `IWebHostBuilder`, e.g https://github.com/AppMetrics/AspNetCore/blob/dev/sandbox/MetricsSandboxMvc/Host.cs#L81

**Comment by caseylobrien** [comment]
Thanks for the link to the sandox, I was merely looking at Samples2 previously. I will look into modifying to configure the App.Metrics off the ```IWebHostBuilder``` instead of startup.cs

The startup.cs looks something like this:

``` csharp
public class Startup
{
    {
        public Startup(IConfiguration configuration) : base(configuration)
        {
        }

        public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            // Configure App metrics and the reporter.
            var metrics = AppMetrics.CreateDefaultBuilder()
                .Configuration.ReadFrom(Configuration)
                .Report.ToLogger()
                .Build();
            services.AddMetrics(metrics);
            services.AddMetricsTrackingMiddleware();
            services.AddMetricsEndpoints();
            services.AddMetricsReportSchedulerEx(TimeSpan.FromSeconds(3));
        }

        protected override void PreConfigure(IApplicationBuilder app, IHostingEnvironment env)
        {
            // Use this prefix for all paths in the service.
            app.UsePathBase("/some-base-path");
        }

        protected override void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseMetricsAllEndpoints();
            app.UseMetricsAllMiddleware();
        }
    }
}
```

**Comment by alhardy** [comment]
Nothing stands out, how did you go with the sanbox project?

If still no luck, I'm happy to throw together an example using your startup code to diagnose.
