### ISSUE TITLE
Metrics per endpoint not reporting paths when MVC not included

### ISSUE THREAD

**Issue by KyleGobel** [AppMetrics/AspNetCore#38]
I'm trying to get some timings and metrics for each of my endpoints, for some reason in the reporting I would only see the method name.

After looking through the code a bit, found this part in `MetricsHttpContextExtensions.cs`

```cs
private static readonly string MetricsCurrentRouteName = "__App.Metrics.CurrentRouteName__"
public static string GetMetricsCurrentRouteName(this HttpContext context)
{
    if (context.Items.TryGetValue(MetricsCurrentRouteName, out var item))
    {
        var route = item as string;
        if (route.IsPresent())
        {
            return $"{context.Request.Method} {route}";
        }
    }

    return context.Request.Method;
}
```

It would appear that it's only pulling out routes that were added to that specific key, and I believe* the only place that's ever called is in the MVC `MetricsResourceFilter.cs` filter.  

I don't know enough about this code base, but was the intention here to actually return:
```cs
return $"{context.Request.Method} {context.Request.Path}";
```
instead of just returning the method name when the mvc filter wasn't involved?

**Comment by lkts** [comment]
Discovered this as well and agree that default fallback to `Request.Path` would be very helpful.
