### ISSUE TITLE
Exception registering JsonSerializerSettings conflicting with AppMetrics

### ISSUE THREAD

**Issue by jchannon** [AppMetrics/AspNetCore#4]
```
public void ConfigureServices(IServiceCollection services)
{
  services.AddSingleton(new JsonSerializerSettings { ContractResolver = new DefaultContractResolver { NamingStrategy = new CamelCaseNamingStrategy() }, NullValueHandling = NullValueHandling.Ignore});
}
```
Using Autofac I got the below error:

```
Cannot choose between multiple constructors with equal length 1 on type 'App.Metrics.Formatters.Json.Serialization.HealthStatusSerializer'. Select the constructor explicitly, with the UsingConstructor() configuration method, when the component is registered.
```

Removing Autofac and just using ASP.NET DI I got a exception about HealthStatusserializer and I think IClock

**Comment by alhardy** [comment]
App Metrics has never registered `JsonSerializerSettings`. The older version of `HealthStatusSerializer` had [two ctors](https://github.com/AppMetrics/Health/blob/2.0.0-refactoring/src/App.Metrics.Health.Formatters.Json/Serialization/HealthStatusSerializer.cs), one of which had `JsonSerializerSettings` injected so DI could not work out which ctor to use. 

This is [no longer the case](https://github.com/AppMetrics/Health/blob/dev/src/App.Metrics.Health.Abstractions/Serialization/HealthStatusSerializer.cs)

**Comment by alhardy** [comment]
This issue was moved to AppMetrics/AspNetCoreHealth#2
