### ISSUE TITLE
Grafana Dashboard for Prometheus 2.0?

### ISSUE THREAD

**Issue by simonwh** [AppMetrics/AspNetCore#53]
Hi,

Did anyone manage to update the Grafana Dashboard Prometheus example by @alhardy to work with Prometheus 2.0 / Grafana 5?

I tried my best, but new to Prometheus / Grafana and didn't mange :-) It doesn't show any panels in the dashboard by default, just blank.

Appreciate any hints and help! Thanks!

**Comment by walliski** [comment]
Hey,

Could it be the same case as here: https://github.com/AppMetrics/AppMetrics/issues/357?

**Comment by simonwh** [comment]
Thanks @walliski, that was indeed it!
