### ISSUE TITLE
App.Metrics.AspNetCore.Tracking

### ISSUE THREAD

**Issue by abhay40711cs** [AppMetrics/AspNetCore#6]
While installing package "App.metrics.AspNetCore.Tracking" for SharePoint solution, it gives error as it is not compatible.
My intent is to use grafana dashboard by the exposed /metrics on Prometheus.

I am having SharePoint solution, can you please suggest is it an enhancement or I am doing something wrong here?

Regards,
Abhay

**Comment by alhardy** [comment]
`App.metrics.AspNetCore.Tracking` targets .NET Standard 2.0, you can find the [compatability matrix here](https://github.com/dotnet/standard/blob/master/docs/versions.md)
